# Generated by Django 5.2.6 on 2025-09-25 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('pass_id', models.IntegerField(primary_key=True, serialize=False)),
                ('completed_pass', models.BooleanField()),
                ('potential_assist', models.BooleanField()),
                ('turnover', models.BooleanField()),
                ('ball_start_loc_x', models.FloatField()),
                ('ball_start_loc_y', models.FloatField()),
                ('ball_end_loc_x', models.FloatField()),
                ('ball_end_loc_y', models.FloatField()),
                ('action_type', models.CharField(max_length=50)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.player')),
            ],
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('shot_id', models.IntegerField(primary_key=True, serialize=False)),
                ('points', models.IntegerField()),
                ('shooting_foul_drawn', models.BooleanField()),
                ('shot_loc_x', models.FloatField()),
                ('shot_loc_y', models.FloatField()),
                ('action_type', models.CharField(max_length=50)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.team'),
        ),
        migrations.CreateModel(
            name='Turnover',
            fields=[
                ('turnover_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tov_loc_x', models.FloatField()),
                ('tov_loc_y', models.FloatField()),
                ('action_type', models.CharField(max_length=50)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.player')),
            ],
        ),
    ]
